local cayo_prep_options = {
	difficulties = {
		{ name = "Normal", value = 126823 },
		{ name = "Hard", value = 131055 },
	},
	approaches = {
		{ name = "Kosatka", value = 65283 },
		{ name = "Alkonost", value = 65413 },
		{ name = "Velum", value = 65289 },
		{ name = "Stealth Annihilator", value = 65425 },
		{ name = "Patrol Boat", value = 65313 },
		{ name = "Longfin", value = 65345 },
		{ name = "All Ways", value = 65535 },
	},
	loadouts = {
		{ name = "Aggressor", value = 1 },
		{ name = "Conspirator", value = 2 },
		{ name = "Crackshot", value = 3 },
		{ name = "Saboteur", value = 4 },
		{ name = "Marksman", value = 5 },
	},
	primary_targets = {
		{ name = "Sinsimito Tequila", value = 0 },
		{ name = "Ruby Necklace", value = 1 },
		{ name = "Bearer Bonds", value = 2 },
		{ name = "Pink Diamond", value = 3 },
		{ name = "Madrazo Files", value = 4 },
		{ name = "Panther Statue", value = 5 },
	},
	secondary_targets = {
		{ name = "None", value = "NONE" },
		{ name = "Cash", value = "CASH" },
		{ name = "Weed", value = "WEED" },
		{ name = "Coke", value = "COKE" },
		{ name = "Gold", value = "GOLD" },
	},
	compound_amounts = {
		{ name = "Empty", value = 0 },
		{ name = "Full", value = 255 },
		{ name = "1", value = 128 },
		{ name = "2", value = 64 },
		{ name = "3", value = 196 },
		{ name = "4", value = 204 },
		{ name = "5", value = 220 },
		{ name = "6", value = 252 },
		{ name = "7", value = 253 },
	},
	island_amounts = {
		{ name = "Empty", value = 0 },
		{ name = "Full", value = 16777215 },
		{ name = "1", value = 8388608 },
		{ name = "2", value = 12582912 },
		{ name = "3", value = 12845056 },
		{ name = "4", value = 12976128 },
		{ name = "5", value = 13500416 },
		{ name = "6", value = 14548992 },
		{ name = "7", value = 16646144 },
		{ name = "8", value = 16711680 },
		{ name = "9", value = 16744448 },
		{ name = "10", value = 16760832 },
		{ name = "11", value = 16769024 },
		{ name = "12", value = 16769536 },
		{ name = "13", value = 16770560 },
		{ name = "14", value = 16770816 },
		{ name = "15", value = 16770880 },
		{ name = "16", value = 16771008 },
		{ name = "17", value = 16773056 },
		{ name = "18", value = 16777152 },
		{ name = "19", value = 16777184 },
		{ name = "20", value = 16777200 },
		{ name = "21", value = 16777202 },
		{ name = "22", value = 16777203 },
		{ name = "23", value = 16777211 },
	},
	arts_amounts = {
		{ name = "Empty", value = 0 },
		{ name = "Full", value = 127 },
		{ name = "1", value = 64 },
		{ name = "2", value = 96 },
		{ name = "3", value = 112 },
		{ name = "4", value = 120 },
		{ name = "5", value = 122 },
		{ name = "6", value = 126 },
	},
	default_values = {
		cash = 83250,
		weed = 135000,
		coke = 202500,
		gold = 333333,
		art = 180000,
	},
}

local casino_prep_options = {
	difficulties = {
		{ name = "Normal", value = 0 },
		{ name = "Hard", value = 1 },
	},
	approaches = {
		{ name = "Silent & Sneaky", value = 1 },
		{ name = "The Big Con", value = 2 },
		{ name = "Aggressive", value = 3 },
	},
	gunmen = {
		{ name = "Karl Abolaji", value = 1 },
		{ name = "Charlie Reed", value = 3 },
		{ name = "Patrick McReary", value = 5 },
		{ name = "Gustavo Mota", value = 2 },
		{ name = "Chester McCoy", value = 4 },
	},
	loadouts = {
		{ name = "Micro SMG (S)", value = 1 },
		{ name = "Machine Pistol (S)", value = 1 },
		{ name = "Micro SMG", value = 1 },
		{ name = "Double Barrel", value = 1 },
		{ name = "Sawed-Off", value = 1 },
		{ name = "Heavy Revolver", value = 1 },
		{ name = "Assault SMG (S)", value = 3 },
		{ name = "Bullpup Shotgun (S)", value = 3 },
		{ name = "Machine Pistol", value = 3 },
		{ name = "Sweeper Shotgun", value = 3 },
		{ name = "Assault SMG", value = 3 },
		{ name = "Pump Shotgun", value = 3 },
		{ name = "Combat PDW", value = 5 },
		{ name = "Assault Rifle (S)", value = 5 },
		{ name = "Sawed-Off", value = 5 },
		{ name = "Compact Rifle", value = 5 },
		{ name = "Heavy Shotgun", value = 5 },
		{ name = "Combat MG", value = 5 },
		{ name = "Carbine Rifle (S)", value = 2 },
		{ name = "Assault Shotgun (S)", value = 2 },
		{ name = "Carbine Rifle", value = 2 },
		{ name = "Assault Shotgun", value = 2 },
		{ name = "Carbine Rifle", value = 2 },
		{ name = "Assault Shotgun", value = 2 },
		{ name = "Pump Shotgun Mk II (S)", value = 4 },
		{ name = "Carbine Rifle Mk II (S)", value = 4 },
		{ name = "SMG Mk II", value = 4 },
		{ name = "Bullpup Rifle Mk II", value = 4 },
		{ name = "Pump Shotgun Mk II", value = 4 },
		{ name = "Assault Rifle Mk II", value = 4 },
	},
	drivers = {
		{ name = "Karim Denz", value = 1 },
		{ name = "Zach Nelson", value = 4 },
		{ name = "Taliana Martinez", value = 2 },
		{ name = "Eddie Toh", value = 3 },
		{ name = "Chester McCoy", value = 5 },
	},
	vehicles = {
		{ name = "Issi Classic", value = 1 },
		{ name = "Asbo", value = 1 },
		{ name = "Blista Kanjo", value = 1 },
		{ name = "Sentinel Classic", value = 1 },
		{ name = "Manchez", value = 4 },
		{ name = "Stryder", value = 4 },
		{ name = "Defiler", value = 4 },
		{ name = "Lectro", value = 4 },
		{ name = "Retinue Mk II", value = 2 },
		{ name = "Drift Yosemite", value = 2 },
		{ name = "Sugoi", value = 2 },
		{ name = "Jugular", value = 2 },
		{ name = "Sultan Classic", value = 3 },
		{ name = "Gauntlet Classic", value = 3 },
		{ name = "Ellie", value = 3 },
		{ name = "Komoda", value = 3 },
		{ name = "Zhaba", value = 5 },
		{ name = "Vagrant", value = 5 },
		{ name = "Outlaw", value = 5 },
		{ name = "Everon", value = 5 },
	},
	hackers = {
		{ name = "Rickie Lukens", value = 1 },
		{ name = "Yohan Blair", value = 3 },
		{ name = "Christian Feltz", value = 2 },
		{ name = "Paige Harris", value = 5 },
		{ name = "Avi Schwartzman", value = 4 },
	},
	masks = {
		{ name = "None", value = 0 },
		{ name = "Geometric Set", value = 1 },
		{ name = "Hunter Set", value = 2 },
		{ name = "Oni Half Mask Set", value = 3 },
		{ name = "Emoji Set", value = 4 },
		{ name = "Ornate Skull Set", value = 5 },
		{ name = "Lucky Fruit Set", value = 6 },
		{ name = "Guerilla Set", value = 7 },
		{ name = "Clown Set", value = 8 },
		{ name = "Animal Set", value = 9 },
		{ name = "Riot Set", value = 10 },
		{ name = "Oni Full Mask Set", value = 11 },
		{ name = "Hockey Set", value = 12 },
	},
	guards = {
		{ name = "Elite", value = 0 },
		{ name = "Pro", value = 1 },
		{ name = "Unit", value = 2 },
		{ name = "Rookie", value = 3 },
	},
	keycards = {
		{ name = "None", value = 0 },
		{ name = "Level 1", value = 1 },
		{ name = "Level 2", value = 2 },
	},
	targets = {
		{ name = "Cash", value = 0 },
		{ name = "Artwork", value = 2 },
		{ name = "Gold", value = 1 },
		{ name = "Diamonds", value = 3 },
	},
}

local heist_state = {
	apartment = {
		cuts = {
			player1 = 100,
			player2 = 0,
			player3 = 0,
			player4 = 0,
		},
		flags = {
			bonus_enabled = false,
			double_rewards_week = false,
			max_payout_enabled = false,
			cut_preset_index = 4,
		},
		refs = {
			p1_slider = nil,
			p2_slider = nil,
			p3_slider = nil,
			p4_slider = nil,
			bonus_toggle = nil,
			double_toggle = nil,
			max_payout_toggle = nil,
			preset_dropdown = nil,
			solo_launch_toggle = nil,
		},
		callbacks = {
			apply_cuts = nil,
			set_bonus = nil,
		},
	},
	cayo = {
		prep_options = cayo_prep_options,
		config = {
			diff = 131055,
			app = 65535,
			wep = 1,
			tgt = 5,
			sec_comp = "GOLD",
			sec_isl = "GOLD",
			amt_comp = 255,
			amt_isl = 16777215,
			paint = 127,
			val_cash = cayo_prep_options.default_values.cash,
			val_weed = cayo_prep_options.default_values.weed,
			val_coke = cayo_prep_options.default_values.coke,
			val_gold = cayo_prep_options.default_values.gold,
			val_art = cayo_prep_options.default_values.art,
			unlock_all_poi = true,
		},
		cuts = {
			host = 100,
			player2 = 100,
			player3 = 100,
			player4 = 100,
		},
		flags = {
			womans_bag_enabled = false,
			remove_crew_cuts_enabled = false,
		},
		refs = {
			womans_bag_toggle = nil,
			unlock_on_apply_toggle = nil,
			difficulty_dropdown = nil,
			approach_dropdown = nil,
			loadout_dropdown = nil,
			primary_target_dropdown = nil,
			compound_target_dropdown = nil,
			compound_amount_dropdown = nil,
			arts_amount_dropdown = nil,
			island_target_dropdown = nil,
			island_amount_dropdown = nil,
			cash_value_slider = nil,
			weed_value_slider = nil,
			coke_value_slider = nil,
			gold_value_slider = nil,
			art_value_slider = nil,
			presets_group = nil,
			remove_crew_cuts_toggle = nil,
			host_slider = nil,
			p2_slider = nil,
			p3_slider = nil,
			p4_slider = nil,
		},
		callbacks = {
			set_womans_bag = nil,
			set_remove_crew_cuts = nil,
		},
	},
	casino = {
		prep_options = casino_prep_options,
		loadout_ranges_by_approach = {
			[1] = { 1, 2 },
			[2] = { 3, 4 },
			[3] = { 5, 6 },
		},
		loadout_ranges_by_gunman_and_approach = {
			[1] = { [1] = { 1, 2 }, [2] = { 3, 4 }, [3] = { 5, 6 } },
			[3] = { [1] = { 7, 8 }, [2] = { 9, 10 }, [3] = { 11, 12 } },
			[5] = { [1] = { 13, 14 }, [2] = { 15, 16 }, [3] = { 17, 18 } },
			[2] = { [1] = { 19, 20 }, [2] = { 21, 22 }, [3] = { 23, 24 } },
			[4] = { [1] = { 25, 26 }, [2] = { 27, 28 }, [3] = { 29, 30 } },
		},
		vehicle_ranges_by_driver = {
			[1] = { 1, 4 },
			[4] = { 5, 8 },
			[2] = { 9, 12 },
			[3] = { 13, 16 },
			[5] = { 17, 20 },
		},
		manual_preps = {
			difficulty = 0,
			approach = 1,
			crew_weapon = 1,
			loadout_slot = 1,
			crew_driver = 1,
			vehicle_slot = 1,
			crew_hacker = 1,
			masks = 4,
			disrupt_shipments = 3,
			key_levels = 2,
			target = 3,
			unlock_all_poi = true,
		},
		flags = {
			remove_crew_cuts_enabled = false,
			autograbber_enabled = false,
		},
		refs = {
			manual_approach_dropdown = nil,
			manual_gunman_dropdown = nil,
			manual_loadout_dropdown = nil,
			manual_driver_dropdown = nil,
			manual_vehicles_dropdown = nil,
			manual_difficulty_dropdown = nil,
			manual_hacker_dropdown = nil,
			manual_masks_dropdown = nil,
			manual_guards_dropdown = nil,
			manual_keycards_dropdown = nil,
			manual_target_dropdown = nil,
			manual_unlock_poi_toggle = nil,
			solo_launch_toggle = nil,
			remove_crew_cuts_toggle = nil,
			autograbber_toggle = nil,
			host_slider = nil,
			p2_slider = nil,
			p3_slider = nil,
			p4_slider = nil,
			presets_group = nil,
		},
		callbacks = {
			set_remove_crew_cuts = nil,
			set_autograbber = nil,
			update_loadout_dropdown = nil,
			update_vehicle_dropdown = nil,
		},
	},
}

return heist_state
