local cayo_prep_options = {
	difficulties = {
		{ name = "Normal", value = 126823 },
		{ name = "Hard", value = 131055 },
	},
	approaches = {
		{ name = "Kosatka", value = 65283 },
		{ name = "Alkonost", value = 65413 },
		{ name = "Velum", value = 65289 },
		{ name = "Stealth Annihilator", value = 65425 },
		{ name = "Patrol Boat", value = 65313 },
		{ name = "Longfin", value = 65345 },
		{ name = "All Ways", value = 65535 },
	},
	loadouts = {
		{ name = "Aggressor", value = 1 },
		{ name = "Conspirator", value = 2 },
		{ name = "Crackshot", value = 3 },
		{ name = "Saboteur", value = 4 },
		{ name = "Marksman", value = 5 },
	},
	primary_targets = {
		{ name = "Sinsimito Tequila", value = 0 },
		{ name = "Ruby Necklace", value = 1 },
		{ name = "Bearer Bonds", value = 2 },
		{ name = "Pink Diamond", value = 3 },
		{ name = "Madrazo Files", value = 4 },
		{ name = "Panther Statue", value = 5 },
	},
	secondary_targets = {
		{ name = "None", value = "NONE" },
		{ name = "Cash", value = "CASH" },
		{ name = "Weed", value = "WEED" },
		{ name = "Coke", value = "COKE" },
		{ name = "Gold", value = "GOLD" },
	},
	compound_amounts = {
		{ name = "Empty", value = 0 },
		{ name = "Full", value = 255 },
		{ name = "1", value = 128 },
		{ name = "2", value = 64 },
		{ name = "3", value = 196 },
		{ name = "4", value = 204 },
		{ name = "5", value = 220 },
		{ name = "6", value = 252 },
		{ name = "7", value = 253 },
	},
	island_amounts = {
		{ name = "Empty", value = 0 },
		{ name = "Full", value = 16777215 },
		{ name = "1", value = 8388608 },
		{ name = "2", value = 12582912 },
		{ name = "3", value = 12845056 },
		{ name = "4", value = 12976128 },
		{ name = "5", value = 13500416 },
		{ name = "6", value = 14548992 },
		{ name = "7", value = 16646144 },
		{ name = "8", value = 16711680 },
		{ name = "9", value = 16744448 },
		{ name = "10", value = 16760832 },
		{ name = "11", value = 16769024 },
		{ name = "12", value = 16769536 },
		{ name = "13", value = 16770560 },
		{ name = "14", value = 16770816 },
		{ name = "15", value = 16770880 },
		{ name = "16", value = 16771008 },
		{ name = "17", value = 16773056 },
		{ name = "18", value = 16777152 },
		{ name = "19", value = 16777184 },
		{ name = "20", value = 16777200 },
		{ name = "21", value = 16777202 },
		{ name = "22", value = 16777203 },
		{ name = "23", value = 16777211 },
	},
	arts_amounts = {
		{ name = "Empty", value = 0 },
		{ name = "Full", value = 127 },
		{ name = "1", value = 64 },
		{ name = "2", value = 96 },
		{ name = "3", value = 112 },
		{ name = "4", value = 120 },
		{ name = "5", value = 122 },
		{ name = "6", value = 126 },
	},
	default_values = {
		cash = 83250,
		weed = 135000,
		coke = 202500,
		gold = 333333,
		art = 180000,
	},
}

local casino_prep_options = {
	difficulties = {
		{ name = "Normal", value = 0 },
		{ name = "Hard", value = 1 },
	},
	approaches = {
		{ name = "Silent & Sneaky", value = 1 },
		{ name = "The Big Con", value = 2 },
		{ name = "Aggressive", value = 3 },
	},
	gunmen = {
		{ name = "Karl Abolaji", value = 1 },
		{ name = "Charlie Reed", value = 3 },
		{ name = "Patrick McReary", value = 5 },
		{ name = "Gustavo Mota", value = 2 },
		{ name = "Chester McCoy", value = 4 },
	},
	loadouts = {
		{ name = "Micro SMG (S)", value = 1 },
		{ name = "Machine Pistol (S)", value = 1 },
		{ name = "Micro SMG", value = 1 },
		{ name = "Double Barrel", value = 1 },
		{ name = "Sawed-Off", value = 1 },
		{ name = "Heavy Revolver", value = 1 },
		{ name = "Assault SMG (S)", value = 3 },
		{ name = "Bullpup Shotgun (S)", value = 3 },
		{ name = "Machine Pistol", value = 3 },
		{ name = "Sweeper Shotgun", value = 3 },
		{ name = "Assault SMG", value = 3 },
		{ name = "Pump Shotgun", value = 3 },
		{ name = "Combat PDW", value = 5 },
		{ name = "Assault Rifle (S)", value = 5 },
		{ name = "Sawed-Off", value = 5 },
		{ name = "Compact Rifle", value = 5 },
		{ name = "Heavy Shotgun", value = 5 },
		{ name = "Combat MG", value = 5 },
		{ name = "Carbine Rifle (S)", value = 2 },
		{ name = "Assault Shotgun (S)", value = 2 },
		{ name = "Carbine Rifle", value = 2 },
		{ name = "Assault Shotgun", value = 2 },
		{ name = "Carbine Rifle", value = 2 },
		{ name = "Assault Shotgun", value = 2 },
		{ name = "Pump Shotgun Mk II (S)", value = 4 },
		{ name = "Carbine Rifle Mk II (S)", value = 4 },
		{ name = "SMG Mk II", value = 4 },
		{ name = "Bullpup Rifle Mk II", value = 4 },
		{ name = "Pump Shotgun Mk II", value = 4 },
		{ name = "Assault Rifle Mk II", value = 4 },
	},
	drivers = {
		{ name = "Karim Denz", value = 1 },
		{ name = "Zach Nelson", value = 4 },
		{ name = "Taliana Martinez", value = 2 },
		{ name = "Eddie Toh", value = 3 },
		{ name = "Chester McCoy", value = 5 },
	},
	vehicles = {
		{ name = "Issi Classic", value = 1 },
		{ name = "Asbo", value = 1 },
		{ name = "Blista Kanjo", value = 1 },
		{ name = "Sentinel Classic", value = 1 },
		{ name = "Manchez", value = 4 },
		{ name = "Stryder", value = 4 },
		{ name = "Defiler", value = 4 },
		{ name = "Lectro", value = 4 },
		{ name = "Retinue Mk II", value = 2 },
		{ name = "Drift Yosemite", value = 2 },
		{ name = "Sugoi", value = 2 },
		{ name = "Jugular", value = 2 },
		{ name = "Sultan Classic", value = 3 },
		{ name = "Gauntlet Classic", value = 3 },
		{ name = "Ellie", value = 3 },
		{ name = "Komoda", value = 3 },
		{ name = "Zhaba", value = 5 },
		{ name = "Vagrant", value = 5 },
		{ name = "Outlaw", value = 5 },
		{ name = "Everon", value = 5 },
	},
	hackers = {
		{ name = "Rickie Lukens", value = 1 },
		{ name = "Yohan Blair", value = 3 },
		{ name = "Christian Feltz", value = 2 },
		{ name = "Paige Harris", value = 5 },
		{ name = "Avi Schwartzman", value = 4 },
	},
	masks = {
		{ name = "None", value = 0 },
		{ name = "Geometric Set", value = 1 },
		{ name = "Hunter Set", value = 2 },
		{ name = "Oni Half Mask Set", value = 3 },
		{ name = "Emoji Set", value = 4 },
		{ name = "Ornate Skull Set", value = 5 },
		{ name = "Lucky Fruit Set", value = 6 },
		{ name = "Guerilla Set", value = 7 },
		{ name = "Clown Set", value = 8 },
		{ name = "Animal Set", value = 9 },
		{ name = "Riot Set", value = 10 },
		{ name = "Oni Full Mask Set", value = 11 },
		{ name = "Hockey Set", value = 12 },
	},
	guards = {
		{ name = "Elite", value = 0 },
		{ name = "Pro", value = 1 },
		{ name = "Unit", value = 2 },
		{ name = "Rookie", value = 3 },
	},
	keycards = {
		{ name = "None", value = 0 },
		{ name = "Level 1", value = 1 },
		{ name = "Level 2", value = 2 },
	},
	targets = {
		{ name = "Cash", value = 0 },
		{ name = "Artwork", value = 2 },
		{ name = "Gold", value = 1 },
		{ name = "Diamonds", value = 3 },
	},
}

local agency_prep_options = {
	contracts = {
		{ name = "None", value = 3 },
		{ name = "Nightclub", value = 4 },
		{ name = "Marina", value = 12 },
		{ name = "Nightlife Leak", value = 28 },
		{ name = "Country Club", value = 60 },
		{ name = "Guest List", value = 123 },
		{ name = "High Soc. Leak", value = 254 },
		{ name = "Davis", value = 508 },
		{ name = "Ballas", value = 1020 },
		{ name = "Sou. Cen. Leak", value = 2044 },
		{ name = "Studio Time", value = 2045 },
		{ name = "Don't # W. Dre", value = 4095 },
	},
}

local autoshop_prep_options = {
	contracts = {
		{ name = "None", value = -1 },
		{ name = "Union Depository", value = 0 },
		{ name = "Superdollar Deal", value = 1 },
		{ name = "Bank Contract", value = 2 },
		{ name = "ECU Job", value = 3 },
		{ name = "Prison Contract", value = 4 },
		{ name = "Agency Deal", value = 5 },
		{ name = "Lost Contract", value = 6 },
		{ name = "Data Contract", value = 7 },
	},
}

local salvageyard_prep_options = {
	robberies = {
		{ name = "Cargo Ship", value = 0 },
		{ name = "Gangbanger", value = 1 },
		{ name = "Duggan", value = 2 },
		{ name = "Podium", value = 3 },
		{ name = "McTony", value = 4 },
	},
	vehicles = {
		{ name = "LM87", value = 1 },
		{ name = "Cinquemila", value = 2 },
		{ name = "Autarch", value = 3 },
		{ name = "Tigon", value = 4 },
		{ name = "Champion", value = 5 },
		{ name = "10F", value = 6 },
		{ name = "SM722", value = 7 },
		{ name = "Omnis e-GT", value = 8 },
		{ name = "Growler", value = 9 },
		{ name = "Deity", value = 10 },
		{ name = "Itali RSX", value = 11 },
		{ name = "Coquette D10", value = 12 },
		{ name = "Jubilee", value = 13 },
		{ name = "Astron", value = 14 },
		{ name = "Comet S2 Cabr.", value = 15 },
		{ name = "Torero", value = 16 },
		{ name = "Cheetah Classic", value = 17 },
		{ name = "Turismo Classic", value = 18 },
		{ name = "Infernus Classic", value = 19 },
		{ name = "Stafford", value = 20 },
		{ name = "GT500", value = 21 },
		{ name = "Viseris", value = 22 },
		{ name = "Mamba", value = 23 },
		{ name = "Coquette Black.", value = 24 },
		{ name = "Stinger GT", value = 25 },
		{ name = "Z-Type", value = 26 },
		{ name = "Broadway", value = 27 },
		{ name = "Vigero ZX", value = 28 },
		{ name = "Buffalo STX", value = 29 },
		{ name = "Ruston", value = 30 },
		{ name = "Gauntl. Hellfire", value = 31 },
		{ name = "Dominator GTT", value = 32 },
		{ name = "Roosevelt Valor", value = 33 },
		{ name = "Swinger", value = 34 },
		{ name = "Stirling GT", value = 35 },
		{ name = "Omnis", value = 36 },
		{ name = "Tropos Rallye", value = 37 },
		{ name = "Jugular", value = 38 },
		{ name = "Patriot Mil-Spec", value = 39 },
		{ name = "Toros", value = 40 },
		{ name = "Caracara 4x4", value = 41 },
		{ name = "Sentinel Classic", value = 42 },
		{ name = "Weevil", value = 43 },
		{ name = "Blista Kanjo", value = 44 },
		{ name = "Eudora", value = 45 },
		{ name = "Kamacho", value = 46 },
		{ name = "Hellion", value = 47 },
		{ name = "Ellie", value = 48 },
		{ name = "Hermes", value = 49 },
		{ name = "Hustler", value = 50 },
		{ name = "Turismo Om.", value = 51 },
		{ name = "Buffalo EVX", value = 52 },
		{ name = "Itali GTO St.", value = 53 },
		{ name = "Virtue", value = 54 },
		{ name = "Ignus", value = 55 },
		{ name = "Zentorno", value = 56 },
		{ name = "Neon", value = 57 },
		{ name = "Furia", value = 58 },
		{ name = "Zorrusso", value = 59 },
		{ name = "Thrax", value = 60 },
		{ name = "Vagner", value = 61 },
		{ name = "Panthere", value = 62 },
		{ name = "Itali GTO", value = 63 },
		{ name = "S80RR", value = 64 },
		{ name = "Tyrant", value = 65 },
		{ name = "Entity MT", value = 66 },
		{ name = "Torero XO", value = 67 },
		{ name = "Neo", value = 68 },
		{ name = "Corsita", value = 69 },
		{ name = "Paragon R", value = 70 },
		{ name = "Franken Stange", value = 71 },
		{ name = "Comet Safari", value = 72 },
		{ name = "FR36", value = 73 },
		{ name = "Hotring Everon", value = 74 },
		{ name = "Komoda", value = 75 },
		{ name = "Tailgater S", value = 76 },
		{ name = "Jester Classic", value = 77 },
		{ name = "Jester RR", value = 78 },
		{ name = "Euros", value = 79 },
		{ name = "ZR350", value = 80 },
		{ name = "Cypher", value = 81 },
		{ name = "Dominator ASP", value = 82 },
		{ name = "Baller ST-D", value = 83 },
		{ name = "Casco", value = 84 },
		{ name = "Drift Yosemite", value = 85 },
		{ name = "Everon", value = 86 },
		{ name = "Penumbra FF", value = 87 },
		{ name = "V-STR", value = 88 },
		{ name = "Dominator GT", value = 89 },
		{ name = "Schlagen GT", value = 90 },
		{ name = "Cavalcade XL", value = 91 },
		{ name = "Clique", value = 92 },
		{ name = "Boor", value = 93 },
		{ name = "Sugoi", value = 94 },
		{ name = "Greenwood", value = 95 },
		{ name = "Brigham", value = 96 },
		{ name = "Issi Rally", value = 97 },
		{ name = "Seminole Fr.", value = 98 },
		{ name = "Kanjo SJ", value = 99 },
		{ name = "Previon", value = 100 },
	},
	modifications = {
		{ name = "Version 1", value = 0 },
		{ name = "Version 2", value = 1 },
		{ name = "Version 3", value = 2 },
		{ name = "Version 4", value = 3 },
		{ name = "Version 5", value = 4 },
	},
	keep_statuses = {
		{ name = "Can't Claim", value = 0 },
		{ name = "Can Claim", value = 1 },
	},
}

local heist_state = {
	apartment = {
		cuts = {
			player1 = 100,
			player2 = 0,
			player3 = 0,
			player4 = 0,
		},
		flags = {
			bonus_enabled = false,
			double_rewards_week = false,
			max_payout_enabled = false,
			cut_preset_index = 4,
		},
		refs = {
			p1_slider = nil,
			p2_slider = nil,
			p3_slider = nil,
			p4_slider = nil,
			bonus_toggle = nil,
			double_toggle = nil,
			max_payout_toggle = nil,
			preset_dropdown = nil,
			solo_launch_toggle = nil,
		},
		callbacks = {
			apply_cuts = nil,
			set_bonus = nil,
		},
	},
	cayo = {
		prep_options = cayo_prep_options,
		config = {
			diff = 131055,
			app = 65535,
			wep = 1,
			tgt = 5,
			sec_comp = "GOLD",
			sec_isl = "GOLD",
			amt_comp = 255,
			amt_isl = 16777215,
			paint = 127,
			val_cash = cayo_prep_options.default_values.cash,
			val_weed = cayo_prep_options.default_values.weed,
			val_coke = cayo_prep_options.default_values.coke,
			val_gold = cayo_prep_options.default_values.gold,
			val_art = cayo_prep_options.default_values.art,
			unlock_all_poi = true,
		},
		cuts = {
			host = 100,
			player2 = 100,
			player3 = 100,
			player4 = 100,
		},
		flags = {
			womans_bag_enabled = false,
			remove_crew_cuts_enabled = false,
		},
		refs = {
			womans_bag_toggle = nil,
			unlock_on_apply_toggle = nil,
			difficulty_dropdown = nil,
			approach_dropdown = nil,
			loadout_dropdown = nil,
			primary_target_dropdown = nil,
			compound_target_dropdown = nil,
			compound_amount_dropdown = nil,
			arts_amount_dropdown = nil,
			island_target_dropdown = nil,
			island_amount_dropdown = nil,
			cash_value_slider = nil,
			weed_value_slider = nil,
			coke_value_slider = nil,
			gold_value_slider = nil,
			art_value_slider = nil,
			presets_group = nil,
			remove_crew_cuts_toggle = nil,
			host_slider = nil,
			p2_slider = nil,
			p3_slider = nil,
			p4_slider = nil,
		},
		callbacks = {
			set_womans_bag = nil,
			set_remove_crew_cuts = nil,
		},
	},
	casino = {
		prep_options = casino_prep_options,
		loadout_ranges_by_approach = {
			[1] = { 1, 2 },
			[2] = { 3, 4 },
			[3] = { 5, 6 },
		},
		loadout_ranges_by_gunman_and_approach = {
			[1] = { [1] = { 1, 2 }, [2] = { 3, 4 }, [3] = { 5, 6 } },
			[3] = { [1] = { 7, 8 }, [2] = { 9, 10 }, [3] = { 11, 12 } },
			[5] = { [1] = { 13, 14 }, [2] = { 15, 16 }, [3] = { 17, 18 } },
			[2] = { [1] = { 19, 20 }, [2] = { 21, 22 }, [3] = { 23, 24 } },
			[4] = { [1] = { 25, 26 }, [2] = { 27, 28 }, [3] = { 29, 30 } },
		},
		vehicle_ranges_by_driver = {
			[1] = { 1, 4 },
			[4] = { 5, 8 },
			[2] = { 9, 12 },
			[3] = { 13, 16 },
			[5] = { 17, 20 },
		},
		manual_preps = {
			difficulty = 0,
			approach = 1,
			crew_weapon = 1,
			loadout_slot = 1,
			crew_driver = 1,
			vehicle_slot = 1,
			crew_hacker = 1,
			masks = 4,
			disrupt_shipments = 3,
			key_levels = 2,
			target = 3,
			unlock_all_poi = true,
		},
		flags = {
			remove_crew_cuts_enabled = false,
			autograbber_enabled = false,
		},
		refs = {
			manual_approach_dropdown = nil,
			manual_gunman_dropdown = nil,
			manual_loadout_dropdown = nil,
			manual_driver_dropdown = nil,
			manual_vehicles_dropdown = nil,
			manual_difficulty_dropdown = nil,
			manual_hacker_dropdown = nil,
			manual_masks_dropdown = nil,
			manual_guards_dropdown = nil,
			manual_keycards_dropdown = nil,
			manual_target_dropdown = nil,
			manual_unlock_poi_toggle = nil,
			solo_launch_toggle = nil,
			remove_crew_cuts_toggle = nil,
			autograbber_toggle = nil,
			host_slider = nil,
			p2_slider = nil,
			p3_slider = nil,
			p4_slider = nil,
			presets_group = nil,
		},
		callbacks = {
			set_remove_crew_cuts = nil,
			set_autograbber = nil,
			update_loadout_dropdown = nil,
			update_vehicle_dropdown = nil,
		},
	},
	doomsday = {
		config = {
			act = 1,
		},
		cuts = {
			player1 = 100,
			player2 = 0,
			player3 = 0,
			player4 = 0,
		},
		cut_enabled = {
			player1 = true,
			player2 = false,
			player3 = false,
			player4 = false,
		},
		flags = {
			max_payout_enabled = false,
			cut_preset_index = 4,
		},
		refs = {
			act_dropdown = nil,
			solo_launch_toggle = nil,
			max_payout_toggle = nil,
			cut_preset_dropdown = nil,
			p1_toggle = nil,
			p2_toggle = nil,
			p3_toggle = nil,
			p4_toggle = nil,
			p1_slider = nil,
			p2_slider = nil,
			p3_slider = nil,
			p4_slider = nil,
			presets_group = nil,
		},
		callbacks = {
			apply_cuts = nil,
			set_max_payout = nil,
			apply_cut_preset = nil,
			set_selected_act = nil,
		},
	},
	agency = {
		prep_options = agency_prep_options,
		config = {
			contract = 3,
			payout = 1000000,
		},
		flags = {
			collect_safe_ee_only = true,
		},
		refs = {
			contract_dropdown = nil,
			payout_slider = nil,
			collect_safe_button = nil,
		},
		callbacks = {
			apply_preps = nil,
			kill_cooldowns = nil,
			apply_payout = nil,
			instant_finish = nil,
		},
	},
	autoshop = {
		prep_options = autoshop_prep_options,
		config = {
			contract = -1,
			contract_index = 1,
			payout = 1000000,
		},
		flags = {
			board_reload_offset_406_supported = true,
			board_reload_offset_408_supported = true,
		},
		refs = {
			contract_dropdown = nil,
			payout_slider = nil,
		},
		callbacks = {
			apply_preps = nil,
			reset_preps = nil,
			redraw_board = nil,
			kill_cooldowns = nil,
			instant_finish = nil,
			apply_payout = nil,
		},
	},
	salvageyard = {
		prep_options = salvageyard_prep_options,
		config = {
			slot1 = { robbery = 0, vehicle = 1, modification = 0, keep = 1 },
			slot2 = { robbery = 1, vehicle = 2, modification = 0, keep = 1 },
			slot3 = { robbery = 2, vehicle = 3, modification = 0, keep = 1 },
			salvage_multiplier = 0.8,
			sell_value_slot1 = 2100000,
			sell_value_slot2 = 2100000,
			sell_value_slot3 = 2100000,
		},
		flags = {
			free_setup = false,
			free_claim = false,
			collect_safe_ee_only = true,
			planning_force_offset_418_supported = true,
			planning_force_offset_416_supported = true,
			planning_reload_offset_537_supported = true,
			planning_reload_offset_535_supported = true,
		},
		refs = {
			slot1_robbery_dropdown = nil,
			slot1_vehicle_dropdown = nil,
			slot1_modification_dropdown = nil,
			slot1_keep_dropdown = nil,
			slot2_robbery_dropdown = nil,
			slot2_vehicle_dropdown = nil,
			slot2_modification_dropdown = nil,
			slot2_keep_dropdown = nil,
			slot3_robbery_dropdown = nil,
			slot3_vehicle_dropdown = nil,
			slot3_modification_dropdown = nil,
			slot3_keep_dropdown = nil,
			free_setup_toggle = nil,
			free_claim_toggle = nil,
			salvage_multiplier_slider = nil,
			sell_value_slot1_slider = nil,
			sell_value_slot2_slider = nil,
			sell_value_slot3_slider = nil,
			collect_safe_button = nil,
		},
		callbacks = {
			apply_slot = nil,
			apply_all_slots = nil,
			complete_preps = nil,
			reset_preps = nil,
			reload_screen = nil,
			set_free_setup = nil,
			set_free_claim = nil,
			instant_finish = nil,
			force_through_error = nil,
			skip_weekly_cooldown = nil,
			collect_safe = nil,
			apply_sell_values = nil,
			apply_sell_multiplier = nil,
			enforce_toggles = nil,
		},
	},
}

return heist_state
