-- ============================================================
-- # Events
-- ============================================================
--
-- ## Functions
--
-- ### subscribe
-- Register a callback to be fired when the event is handled, returning a callback id.
-- ---@param type events.event
-- ---@param callback function(data)
-- function events.subscribe(type, callback): integer
--
-- ### unsubscribe
-- Delete a callback using the id returned from subscribe.
-- ---@param id integer
-- function events.subscribe(id): nil
--
-- ### get
-- Returns an event for a given callback id.
-- ---@param id integer
-- function events.get(id) -> event
--
-- ## Types
--
-- ### event
-- | Type     | Name    |
-- |----------|---------|
-- | bool     | enabled |
-- | function | fn      |
--
-- ### player_join
-- | Type    | Name   |
-- |---------|--------|
-- | player  | player |
-- | integer | slot   |
--
-- ### player_leave
-- | Type    | Name   |
-- |---------|--------|
-- | player  | player |
-- | integer | slot   |
--
-- ### player_flagged
-- | Type    | Name   |
-- |---------|--------|
-- | player  | player |
-- | string  | reason |
--
-- ### log
-- | Type   | Name   |
-- |--------|--------|
-- | string | text   |
-- | color  | color  |
-- | string | prefix |
-- | string | time   |
--
-- ### scroll
-- | Type   | Name   |
-- |--------|--------|
-- | number | offset |
--
-- ### key_press
-- | Type    | Name |
-- |---------|------|
-- | integer | key  |
--
-- ### char_press
-- | Type   | Name |
-- |--------|------|
-- | string | char |
--
-- ## Constants
--
-- ### event
-- events.event.player_join
-- events.event.player_leave
-- events.event.player_flagged
-- events.event.log
-- events.event.scroll
-- events.event.key_press
-- events.event.char_press
--
-- ### Example
-- ```lua
-- events.subscribe(events.event.key_press, function(data)
--     print('key pressed: ' .. tostring(data.key))
-- end)
--
-- events.subscribe(events.event.char_press, function(data)
--     print('char pressed: ' .. data.char)
-- end)
--
-- events.subscribe(events.event.scroll, function(data)
--     print('scroll: ' .. tostring(data.offset))
-- end)
-- ```
---@class events_event_enum
---@field player_join    integer
---@field player_leave   integer
---@field player_flagged integer
---@field log            integer
---@field scroll         integer
---@field key_press      integer
---@field char_press     integer
---@class event
---@field enabled boolean
---@field fn      function
---@class event_data_player_join
---@field player player
---@field slot   integer
---@class event_data_player_leave
---@field player player
---@field slot   integer
---@class event_data_player_flagged
---@field player player
---@field reason string
---@class event_data_log
---@field text   string
---@field color  color
---@field prefix string
---@field time   string
---@class event_data_scroll
---@field offset number
---@class event_data_key_press
---@field key integer
---@class event_data_char_press
---@field char string
---@class events
---@field event events_event_enum
events = {}
--- Register a callback to be fired when the event is handled, returning a callback id.
---@param type integer
---@param callback fun(data: any)
---@return integer
function events.subscribe(type, callback) end
--- Delete a callback using the id returned from subscribe.
---@param id integer
---@return nil
function events.unsubscribe(id) end
--- Returns an event for a given callback id.
---@param id integer
---@return event
function events.get(id) end
