-- ============================================================
-- # GUI
-- ============================================================
--
-- ## Functions
--
-- ### push_clip
-- Pushes a clip rect.
-- ---@param pos vec2
-- ---@param scale vec2
-- function gui.push_clip(pos, scale): nil
--
-- ### pop_clip
-- Pops a clip rect.
-- function gui.pop_clip(): nil
--
-- ### line
-- Draws a 2D line.
-- ---@param from vec2
-- ---@param to vec2
-- ---@param thickness number
-- ---@param color color
-- function gui.line(from, to, thickness, color): nil
--
-- ### circle
-- Draws a circle.
-- ---@param pos vec2
-- ---@param radius number
-- ---@param color color
-- function gui.circle(pos, radius, color): nil
--
-- ### image
-- Draws an image.
-- ---@param texture texture
-- ---@param pos vec2
-- ---@param scale vec2
-- ---@param color color
-- function gui.image(texture, pos, scale, color): nil
--
-- ### image_rounded
-- Draws a rounded image.
-- ---@param texture texture
-- ---@param pos vec2
-- ---@param scale vec2
-- ---@param color color
-- ---@param rounding number
-- ---@param flags gui.rounding|integer
-- function gui.image_rounded(texture, pos, scale, color, rounding?, flags?): nil
--
-- ### image_rotated
-- Draws a rotated image.
-- ---@param texture texture
-- ---@param pos vec2
-- ---@param scale vec2
-- ---@param color color
-- ---@param degrees number
-- function gui.image_rotated(texture, pos, scale, color, degrees): nil
--
-- ### rebuild
-- Rebuild the font atlas.
-- function gui.rebuild(): nil
--
-- ### load_image
-- Loads an image.
-- ---@param path string
-- function gui.load_image(path): texture
--
-- ### load_font
-- Loads a font.
-- ---@param path string
-- ---@param scale number
-- function gui.load_font(path, scale): font
--
-- ### text
-- Creates an instance of text.
-- ---@param str string
-- function gui.text(str): text
--
-- ### rect
-- Creates an instance of rect.
-- ---@param pos vec2
-- ---@param scale vec2
-- function gui.rect(pos, scale): rect
--
-- ### text_size
-- Gets the width and height of some text.
-- ---@param text string
-- ---@param scale number
-- ---@param options? { wrap: number, font: font }
-- function gui.text_size(text, scale, options?): vec2
--
-- ## Types
--
-- ### text
-- function text:draw(): text
-- function text:get_size(): vec2
-- ---@param pos vec2
-- function text:position(pos): text
-- ---@param color color
-- function text:color(color): text
-- ---@param wrap number
-- function text:wrap(wrap): text
-- ---@param scale number
-- function text:scale(scale): text
-- ---@param justify gui.justify
-- function text:justify(justify): text
-- ---@param font font
-- function text:font(font): text
--
-- ### rect
-- function rect:draw(): rect
-- function rect:filled(): rect
-- ---@param color color
-- function rect:color(color): rect
-- ---@param thickness number
-- ---@param color color
-- function rect:outline(thickness, color): rect
-- ---@param rounding number
-- ---@param flags? gui.rounding|integer
-- function rect:rounding(rounding, flags?): rect
-- ---@param upr_left color
-- ---@param upr_right color
-- ---@param bot_right color
-- ---@param bot_left color
-- function rect:multicolors(upr_left, upr_right, bot_right, bot_left): rect
--
-- ### color
-- | Type    | Name |
-- |---------|------|
-- | integer | r    |
-- | integer | g    |
-- | integer | b    |
-- | number  | rf   |
-- | number  | gf   |
-- | number  | bf   |
--
-- ### texture
-- | Type   | Name  |
-- |--------|-------|
-- | vec2   | scale |
-- | string | name  |
-- | string | path  |
--
-- ### font
-- | Type   | Name  |
-- |--------|-------|
-- | number | scale |
-- | string | path  |
--
-- ## Constants
--
-- ### justify
-- gui.justify.left
-- gui.justify.center
-- gui.justify.right
--
-- ### rounding
-- gui.rounding.top_left
-- gui.rounding.top_right
-- gui.rounding.bottom_left
-- gui.rounding.bottom_right
--
-- ## Example
-- ```lua
-- util.create_thread(function()
--     gui.rect(vec2(100.0, 100.0), vec2(100.0, 100.0))
--         :filled()
--         :color(color(255, 255, 255, 100))
--         :draw()
--     gui.text('test')
--         :position(vec2(100.0, 100.0))
--         :color(color(255, 255, 255, 100))
--         :draw()
-- end)
-- ```
---@class color
---@field r  integer
---@field g  integer
---@field b  integer
---@field rf number
---@field gf number
---@field bf number
---@class texture
---@field scale vec2
---@field name  string
---@field path  string
---@class font
---@field scale number
---@field path  string
---@class gui_justify
---@field left   integer
---@field center integer
---@field right  integer
---@class gui_rounding
---@field top_left     integer
---@field top_right    integer
---@field bottom_left  integer
---@field bottom_right integer
---@class text
text = {}
---@return text
function text:draw() end
---@return vec2
function text:get_size() end
---@param pos vec2
---@return text
function text:position(pos) end
---@param c color
---@return text
function text:color(c) end
---@param wrap number
---@return text
function text:wrap(wrap) end
---@param scale number
---@return text
function text:scale(scale) end
---@param justify integer
---@return text
function text:justify(justify) end
---@param f font
---@return text
function text:font(f) end
---@class rect
rect = {}
---@return rect
function rect:draw() end
---@return rect
function rect:filled() end
---@param c color
---@return rect
function rect:color(c) end
---@param thickness number
---@param c color
---@return rect
function rect:outline(thickness, c) end
---@param rounding number
---@param flags? integer
---@return rect
function rect:rounding(rounding, flags) end
---@param upr_left  color
---@param upr_right color
---@param bot_right color
---@param bot_left  color
---@return rect
function rect:multicolors(upr_left, upr_right, bot_right, bot_left) end
---@class gui
---@field justify  gui_justify
---@field rounding gui_rounding
gui = {}
--- Pushes a clip rect.
---@param pos   vec2
---@param scale vec2
---@return nil
function gui.push_clip(pos, scale) end
--- Pops a clip rect.
---@return nil
function gui.pop_clip() end
--- Draws a 2D line.
---@param from      vec2
---@param to        vec2
---@param thickness number
---@param c         color
---@return nil
function gui.line(from, to, thickness, c) end
--- Draws a circle.
---@param pos    vec2
---@param radius number
---@param c      color
---@return nil
function gui.circle(pos, radius, c) end
--- Draws an image.
---@param tex   texture
---@param pos   vec2
---@param scale vec2
---@param c     color
---@return nil
function gui.image(tex, pos, scale, c) end
--- Draws a rounded image.
---@param tex      texture
---@param pos      vec2
---@param scale    vec2
---@param c        color
---@param rounding? number
---@param flags?   integer
---@return nil
function gui.image_rounded(tex, pos, scale, c, rounding, flags) end
--- Draws a rotated image.
---@param tex     texture
---@param pos     vec2
---@param scale   vec2
---@param c       color
---@param degrees number
---@return nil
function gui.image_rotated(tex, pos, scale, c, degrees) end
--- Rebuilds the font atlas.
---@return nil
function gui.rebuild() end
--- Loads an image from path and returns a texture.
---@param path string
---@return texture
function gui.load_image(path) end
--- Loads a font from path at the given scale.
---@param path  string
---@param scale number
---@return font
function gui.load_font(path, scale) end
--- Creates an instance of text.
---@param str string
---@return text
function gui.text(str) end
--- Creates an instance of rect.
---@param pos   vec2
---@param scale vec2
---@return rect
function gui.rect(pos, scale) end
--- Gets the width and height of some text.
---@param txt     string
---@param scale   number
---@param options? { wrap: number, font: font }
---@return vec2
function gui.text_size(txt, scale, options) end
