--- ============================================================
--- Lexis Lua API — EmmyLua Stub File
--- Source: https://docs.lexis.re/
--- ============================================================
-- ============================================================
-- # Welcome
-- ============================================================
--
-- ## Welcome to the Lexis Lua documentation
--
-- Whether you're a seasoned developer or just dipping your toes into Lua,
-- this documentation is your go-to resource for navigating the Lexis Lua API.
--
-- To kickstart your development experience, we highly recommend utilizing our
-- natives.lua file, a handy collection of game script functions. Incorporating
-- this into your projects will not only streamline your workflow but also
-- enhance your productivity.
--
-- Please refer to our example projects if you get stuck.
--   natives.lua : https://docs.lexis.re/natives.lua
--   example.zip : https://docs.lexis.re/example.zip
-- ============================================================
-- # Environment
-- ============================================================
--
-- Information on the environment around your script.
--
-- ## Permissions
--
-- When a script is loaded, a set of permissions are available to toggle.
-- If you're using certain game mechanics, such as running transactions,
-- it's recommended to check that permissions were given first.
--
-- ### Permission Layout
--
-- | Flag         | Purpose                |
-- |--------------|------------------------|
-- | natives      | Calling natives        |
-- | global_read  | Reading script globals |
-- | global_write | Writing script globals |
-- | local_read   | Reading script locals  |
-- | local_write  | Writing script locals  |
-- | memory_read  | Reading game memory    |
-- | memory_write | Writing game memory    |
-- | https        | Sending web requests   |
-- | file_read    | Reading files          |
-- | file_write   | Writing files          |
-- | stat_read    | Reading stats          |
-- | stat_write   | Writing stats          |
-- | transactions | Running transactions   |
--
-- > **Note:** In most cases, attempting to use a function without permissions
-- > will either do nothing or return an empty state.
--
-- ```lua
-- if this.permissions() & permission.transactions == 0 then
--     print('Exiting script, need transactions')
--     this.unload()
--     return
-- end
-- ```
--
-- ## JOAAT
--
-- If you're looking for a faster method of hashing text using the games
-- native hashing method (JOAAT), you can use joaat.
--
-- ```lua
-- local hash = joaat('adder')
-- ```
--- Returns the permission bitmask for the current script.
---@return integer
function this.permissions() end
--- Unloads the current script.
---@return nil
function this.unload() end
--- Hashes a string using the JOAAT algorithm.
---@param str string
---@return integer
function joaat(str) end
