-- ============================================================
-- # Invoker
-- ============================================================
--
-- ## Functions
--
-- ### call
-- Invoke a native.
-- ---@param hash integer
-- ---@param args? ...
-- function invoker.call(hash, args?): native_invoke
--
-- ## Types
--
-- ### native_invoke
-- | Type           | Name     |
-- |----------------|----------|
-- | integer        | int      |
-- | integer        | int64    |
-- | number         | float    |
-- | bool           | bool     |
-- | string         | str      |
-- | memory_address | address  |
-- | scr_vec3       | scr_vec3 |
--
-- ## Example
-- ```lua
-- util.create_thread(function()
--     local ped = invoker.call(0xD80958FC74E988A6).int -- PLAYER_PED_ID
--     local coords = invoker.call(0x3FEF770D40960D5A, ped, false).scr_vec3 -- GET_ENTITY_COORDS
--     invoker.call(0xF2A1B2771A01DBD4, coords.x, coords.y, coords.z, 0, 255.0, 0, 1000.0, 1.0) -- DRAW_LIGHT_WITH_RANGE
-- end)
-- ```

---@class native_invoke
---@field int     integer
---@field int64   integer
---@field float   number
---@field bool    boolean
---@field str     string
---@field address memory_address
---@field scr_vec3 scr_vec3

---@class invoker
invoker = {}

--- Invoke a native.
---@param hash integer
---@param ... any
---@return native_invoke
function invoker.call(hash, ...) end
