-- ============================================================
-- # Notify
-- ============================================================
--
-- ## Functions
--
-- ### push
-- Pushes a notification to the queue.
-- ---@param title string
-- ---@param desc string
-- ---@param options? { time: number, icon: notify.icon }
-- function notify.push(title, desc, options?): nil
--
-- ### clear
-- Clears the notify queue.
-- function notify.clear(): nil
--
-- ## Constants
--
-- ### icon
-- notify.icon.info
-- notify.icon.modder
-- notify.icon.player_join
-- notify.icon.player_leave
-- notify.icon.protections
-- notify.icon.spawner
-- notify.icon.hotkey
-- notify.icon.hazard
-- notify.icon.player_spawn
-- notify.icon.spoofing
-- notify.icon.join_failed
-- notify.icon.join_blocking
-- notify.icon.tracking
--
-- ### Example
-- ```lua
-- notify.push('My Script', 'Test from my script!', { time=10000, icon=notify.icon.hazard })
-- notify.push('My Script', 'Test from my script!') -- defaults to { time=6000, icon=notify.icon.info }
-- ```
---@class notify_icon
---@field info          integer
---@field modder        integer
---@field player_join   integer
---@field player_leave  integer
---@field protections   integer
---@field spawner       integer
---@field hotkey        integer
---@field hazard        integer
---@field player_spawn  integer
---@field spoofing      integer
---@field join_failed   integer
---@field join_blocking integer
---@field tracking      integer
---@class notify
---@field icon notify_icon
notify = {}
--- Pushes a notification to the queue.
---@param title string
---@param desc string
---@param options? { time: number, icon: integer }
---@return nil
function notify.push(title, desc, options) end
--- Clears the notify queue.
---@return nil
function notify.clear() end
