-- ============================================================
-- # Players
-- ============================================================
--
-- ## Functions
--
-- ### me
-- Return your local player.
-- function players.me(): player
--
-- ### target
-- Return the selected player from inside Lexis.
-- function players.target(): player
--
-- ### is_target_session
-- If the current Lexis player target is the session.
-- function players.is_target_session(): bool
--
-- ### get
-- Return a player via index.
-- ---@param index integer
-- function players.get(index): player
--
-- ### list
-- Return a list of player for each player in the session.
-- function players.list(): player[]
--
-- ## Types
--
-- ### player
-- | Type           | Name              |
-- |----------------|-------------------|
-- | string         | name              |
-- | integer        | id                |
-- | integer        | ped               |
-- | integer        | vehicle           |
-- | integer        | weapon_entity     |
-- | integer        | entity            |
-- | integer        | model             |
-- | integer        | vehicle_model     |
-- | integer        | weapon_model      |
-- | integer        | last_synced_model |
-- | number         | heading           |
-- | scr_vec3       | coords            |
-- | scr_vec3       | rotation          |
-- | scr_vec3       | cam_rotation      |
-- | vec2           | waypoint          |
-- | memory_address | net_player        |
-- | bool           | connected         |
-- | bool           | exists            |
-- | bool           | alive             |
-- | bool           | in_vehicle        |
-- | bool           | weapon_in_hand    |
-- | bool           | shooting          |
-- | bool           | driver            |
-- | bool           | aiming            |
-- | bool           | active_bounty     |
-- | bool           | freemode_host     |
-- | bool           | friend            |
-- | bool           | controller        |
-- | bool           | modder            |
-- | integer        | bounty            |
-- | integer        | rank              |
-- | integer        | cash              |
-- | integer        | bank              |
-- | integer        | wallet            |
-- | number         | kd                |
-- | integer        | playtime          |
-- | integer        | blacklist         |
-- | bool           | force_entity_sync |
-- | integer        | rockstar_id       |
-- | integer        | ip_address        |
-- | bool           | in_ceo            |
-- | bool           | boss              |
-- | integer        | host_token        |
-- | bool           | in_interior       |
-- | integer        | gang_id           |
--
-- ---@param object memory_address
-- ---@param type net_object|integer
-- ---@param node data_node|integer
-- function player:force_sync_node(object, type, node): nil
--
-- ---@param coords vec3|scr_vec3
-- function player:teleport(coords): nil
--
-- ---@param event_hash integer
-- ---@param params table
-- function player:script_event(event_hash, params): nil
--
-- ---@param type net_object|integer
-- ---@param node data_node|integer
-- ---@param mods table
-- function player:modify_outgoing_node(type, node, mods): nil
--
-- ## Example
-- ```lua
-- local target = players.target()
-- mods = {}
-- mods[0x119] = {node_data_type.bool, true}
-- target:modify_outgoing_node(net_object.automobile, data_node.vehicle_control, mods)
-- target:force_sync_node(game.net_obj_from_entity(players.me().vehicle), net_object.automobile, data_node.vehicle_control)
-- ```
---@class player
---@field name              string
---@field id                integer
---@field ped               integer
---@field vehicle           integer
---@field weapon_entity     integer
---@field entity            integer
---@field model             integer
---@field vehicle_model     integer
---@field weapon_model      integer
---@field last_synced_model integer
---@field heading           number
---@field coords            scr_vec3
---@field rotation          scr_vec3
---@field cam_rotation      scr_vec3
---@field waypoint          vec2
---@field net_player        memory_address
---@field connected         boolean
---@field exists            boolean
---@field alive             boolean
---@field in_vehicle        boolean
---@field weapon_in_hand    boolean
---@field shooting          boolean
---@field driver            boolean
---@field aiming            boolean
---@field active_bounty     boolean
---@field freemode_host     boolean
---@field friend            boolean
---@field controller        boolean
---@field modder            boolean
---@field bounty            integer
---@field rank              integer
---@field cash              integer
---@field bank              integer
---@field wallet            integer
---@field kd                number
---@field playtime          integer
---@field blacklist         integer
---@field force_entity_sync boolean
---@field rockstar_id       integer
---@field ip_address        integer
---@field in_ceo            boolean
---@field boss              boolean
---@field host_token        integer
---@field in_interior       boolean
---@field gang_id           integer
player = {}
--- Force sync a node for this player's object.
---@param object memory_address
---@param type   integer
---@param node   integer
---@return nil
function player:force_sync_node(object, type, node) end
--- Teleport this player to coords.
---@param coords vec3|scr_vec3
---@return nil
function player:teleport(coords) end
--- Send a script event to this player.
---@param event_hash integer
---@param params     table
---@return nil
function player:script_event(event_hash, params) end
--- Modify an outgoing sync node for this player.
---@param type integer
---@param node integer
---@param mods table
---@return nil
function player:modify_outgoing_node(type, node, mods) end
---@class players
players = {}
--- Return your local player.
---@return player
function players.me() end
--- Return the selected player from inside Lexis.
---@return player
function players.target() end
--- If the current Lexis player target is the session.
---@return boolean
function players.is_target_session() end
--- Return a player via index.
---@param index integer
---@return player
function players.get(index) end
--- Return a list of players for each player in the session.
---@return player[]
function players.list() end
