-- ============================================================
-- # Regex
-- ============================================================
--
-- ## Functions
--
-- ### regex
-- Create a regex instance with a given pattern.
-- ---@param pattern string
-- function regex(pattern): regex
--
-- ## Types
--
-- ### find_all
-- ---@param subject string
-- function regex:find_all(subject): string[][]
--
-- ### Example
-- ```lua
-- local r = regex('a*b')
-- print(r.find_all('aaab aab ab'))
-- -- {{"aaab"}, {"aab"}, {"ab"}}
-- ```
---@class regex
---@return regex
function regex(pattern) end
--- Find all matches in subject.
---@param subject string
---@return string[][]
function regex:find_all(subject) end
